cluster: "profiles/ebio-cluster/jobsubmit"
cluster-config: "profiles/ebio-cluster/cluster.yml"
cluster-status: "profiles/ebio-cluster/jobstatus"
jobscript: "profiles/ebio-cluster/jobscript.sh"
jobs: 128
#immediate-submit: true
verbose: false
#notemp: true
use-conda: true
conda-frontend: mamba
rerun-incomplete: true
keep-going: true
max-jobs-per-second: 5
max-status-checks-per-second: 5
latency-wait: 60
local-cores: 16
restart-times: 3
scheduler: greedy
greediness: 0.1
printshellcmds: true
